name: Run Selenium Tests on GCP VM

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests on GCP via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd selenium-gcp
            git pull origin main
            mvn clean test
            
            # Upload the report to GCS
            
            if [ -f test-output/ExtentReport.html ]; then
                TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                gsutil cp test-output/ExtentReport.html gs://selenium-test-reports/reports/ExtentReport_$TIMESTAMP.html
                gsutil cp -a public-read test-output/ExtentReport.html gs://selenium-test-reports/reports/ExtentReport_latest.html
            fi
            
      - name: Send Email Notification
        if: always()
        run: |
            STATUS="✅ Passed"
            if [ "${{ job.status }}" != "success" ]; then
                STATUS="❌ Failed"
            fi

            REPORT_LINK="https://storage.googleapis.com/selenium-test-reports/reports/ExtentReport_latest.html"
            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
            
            echo "From: Selenium Tests <${{ secrets.EMAIL_USER }}>" > email.txt
            echo "To: ${{ secrets.EMAIL_TO }}" >> email.txt
            echo "Subject: Selenium Test Run: $STATUS" >> email.txt
            echo "" >> email.txt
            echo "Selenium Test Status: $STATUS" >> email.txt
            echo "Report Link: $REPORT_LINK" >> email.txt
            echo "Run Time: $TIMESTAMP" >> email.txt
            
            curl -s --url "smtps://smtp.gmail.com:465" --ssl-reqd \
            --mail-from "${{ secrets.EMAIL_USER }}" \
            --mail-rcpt "${{ secrets.EMAIL_TO }}" \
            --upload-file email.txt \
            --user "${{ secrets.EMAIL_USER }}:${{ secrets.EMAIL_PASSWORD }}"
